version: '3'
services:
  postgres_database:
  image: postgres
  container_name: 'container_pg'
  enviroment:
   - POSTGRES_USER=admin
   - POSTGRES_PASSWORD=admin
   - POSTGRES_DB=coder_db
  ports:
   - '5432:5432'
  volumes:
   - './db:var/lib/postgresql/data'